import { User, Notice } from './types';

const now = Date.now();
const H = 3600_000;
const D = 24 * H;

export const SEED_USERS: User[] = [
  {
    id: 'u_admin',
    name: 'Dr. Elena Marsh',
    email: 'admin@crestwood.edu',
    password: 'admin123',
    role: 'admin',
    color: '#F59E0B',
    subject: 'Principal',
    createdAt: now - 400 * D,
  },
  {
    id: 'u_t1',
    name: 'Daniel Okafor',
    email: 'teacher@crestwood.edu',
    password: 'teach123',
    role: 'teacher',
    color: '#10B981',
    subject: 'Mathematics',
    createdAt: now - 300 * D,
  },
  {
    id: 'u_t2',
    name: 'Priya Raman',
    email: 'priya@crestwood.edu',
    password: 'teach123',
    role: 'teacher',
    color: '#8B5CF6',
    subject: 'Physics',
    createdAt: now - 280 * D,
  },
  {
    id: 'u_s1',
    name: 'Ava Thompson',
    email: 'student@crestwood.edu',
    password: 'stud123',
    role: 'student',
    color: '#0EA5E9',
    subject: 'Grade 11 · Maple House',
    createdAt: now - 200 * D,
  },
];

export const SEED_NOTICES: Notice[] = [
  {
    id: 'n_exams',
    title: 'Mid-Term Examination Schedule Released',
    body:
      'The mid-term examination timetable for all grades is now finalised.\n\n• Grades 6–8 begin Monday, 28 September\n• Grades 9–12 begin Wednesday, 30 September\n• All exams start at 9:00 AM sharp in the Main Hall\n\nStudents must carry their ID cards and arrive 20 minutes early. The detailed grade-wise timetable has been posted on every floor notice board and is attached below. Reach out to your class teacher for any clashes.',
    category: 'Exams',
    priority: 'urgent',
    images: ['https://picsum.photos/seed/crest-exam/900/600'],
    design: null,
    authorId: 'u_admin',
    authorName: 'Dr. Elena Marsh',
    authorRole: 'admin',
    createdAt: now - 5 * H,
    pinned: true,
    likes: ['u_t1', 'u_t2', 'u_s1'],
    views: ['u_t1', 'u_t2', 'u_s1'],
  },
  {
    id: 'n_scifair',
    title: 'Annual Science Fair — Registrations Open',
    body:
      'Calling all inventors, tinkerers and curious minds! The Crestwood Annual Science Fair returns on 17 October in the Innovation Wing.\n\nTeams of up to 3 students may register. Categories this year:\n• Robotics & Automation\n• Environmental Science\n• Physics in Everyday Life\n• Open Innovation\n\nRegister with me in Lab 2 before 3 October. Top three teams represent Crestwood at the Regional STEM Championship!',
    category: 'Events',
    priority: 'important',
    images: [
      'https://picsum.photos/seed/crest-sci1/900/600',
      'https://picsum.photos/seed/crest-sci2/900/600',
    ],
    design: null,
    authorId: 'u_t2',
    authorName: 'Priya Raman',
    authorRole: 'teacher',
    createdAt: now - 26 * H,
    pinned: true,
    likes: ['u_s1', 'u_admin'],
    views: ['u_s1', 'u_admin', 'u_t1'],
  },
  {
    id: 'n_library',
    title: 'New Library Hours',
    body:
      'Starting next week, the Whitfield Library will stay open until 6:30 PM on weekdays. Saturday reading hours: 9 AM – 1 PM. The silent study loft on the mezzanine is now bookable in 1-hour slots at the front desk.',
    category: 'General',
    priority: 'normal',
    images: [],
    design: {
      bg: 'ocean',
      font: 'serif',
      align: 'center',
      size: 'M',
      titleColor: '#FFFFFF',
      bodyColor: 'rgba(255,255,255,0.92)',
      highlight: null,
      sticker: '📚',
    },
    authorId: 'u_t1',
    authorName: 'Daniel Okafor',
    authorRole: 'teacher',
    createdAt: now - 2 * D,
    pinned: false,
    likes: ['u_s1'],
    views: ['u_s1', 'u_t2'],
  },
  {
    id: 'n_founders',
    title: "Founders' Day Holiday — 2 October",
    body:
      'Crestwood Academy will remain closed on Friday, 2 October in observance of Founders\' Day. Classes resume Monday as usual. We wish every family a restful long weekend!',
    category: 'Holidays',
    priority: 'important',
    images: [],
    design: {
      bg: 'gold',
      font: 'serif',
      align: 'center',
      size: 'L',
      titleColor: '#FFFFFF',
      bodyColor: 'rgba(255,255,255,0.94)',
      highlight: '#B45309',
      sticker: '🎉',
    },
    authorId: 'u_admin',
    authorName: 'Dr. Elena Marsh',
    authorRole: 'admin',
    createdAt: now - 3 * D,
    pinned: false,
    likes: ['u_s1', 'u_t1', 'u_t2'],
    views: ['u_s1', 'u_t1', 'u_t2'],
  },
  {
    id: 'n_football',
    title: 'Inter-House Football Finals This Friday',
    body:
      'Maple House takes on Cedar House in the season finale! Kick-off at 4 PM on the main field. Wear your house colours — the loudest stand wins the Spirit Cup. Snack stalls run by the Grade 12 fundraising committee will be open from 3 PM.',
    category: 'Sports',
    priority: 'normal',
    images: [
      'https://picsum.photos/seed/crest-foot1/900/600',
      'https://picsum.photos/seed/crest-foot2/900/600',
      'https://picsum.photos/seed/crest-foot3/900/600',
    ],
    design: null,
    authorId: 'u_t1',
    authorName: 'Daniel Okafor',
    authorRole: 'teacher',
    createdAt: now - 4 * D,
    pinned: false,
    likes: ['u_s1', 'u_t2'],
    views: ['u_s1', 'u_t2', 'u_admin'],
  },
  {
    id: 'n_robotics',
    title: 'Robotics Club Open Evening',
    body:
      'Curious about building robots? Drop into Lab 4 on Thursday at 4:30 PM. See our line-following bots in action, meet the team, and sign up for the beginner track — no experience needed. Parents welcome!',
    category: 'Clubs',
    priority: 'normal',
    images: ['https://picsum.photos/seed/crest-robot/900/600'],
    design: null,
    authorId: 'u_t2',
    authorName: 'Priya Raman',
    authorRole: 'teacher',
    createdAt: now - 5 * D,
    pinned: false,
    likes: ['u_s1'],
    views: ['u_s1', 'u_t1'],
  },
  {
    id: 'n_cafeteria',
    title: 'Cafeteria Menu Refresh & Allergy Notices',
    body:
      'From Monday the cafeteria introduces a new seasonal menu with two vegetarian mains daily and a fresh salad bar. Full allergen charts are displayed at every counter. Students with dietary requirements should update their profile with the school nurse by Friday.',
    category: 'General',
    priority: 'important',
    images: ['https://picsum.photos/seed/crest-food/900/600'],
    design: null,
    authorId: 'u_admin',
    authorName: 'Dr. Elena Marsh',
    authorRole: 'admin',
    createdAt: now - 6 * D,
    pinned: false,
    likes: ['u_t1'],
    views: ['u_t1', 'u_s1'],
  },
  {
    id: 'n_olympiad',
    title: 'Math Olympiad Practice Sheets — Week 4',
    body:
      'Week 4 practice sets (Number Theory + Combinatorics) are available for collection outside Room 12. Solutions will be discussed in Wednesday\'s lunchtime session. Remember: elegance beats brute force. Bring your toughest questions!',
    category: 'Exams',
    priority: 'normal',
    images: [],
    design: null,
    authorId: 'u_t1',
    authorName: 'Daniel Okafor',
    authorRole: 'teacher',
    createdAt: now - 8 * D,
    pinned: false,
    likes: ['u_s1', 'u_admin'],
    views: ['u_s1', 'u_admin', 'u_t2'],
  },
];
